#  Name of workflow
name: Backup workflow

# When workflow is triggered
on:
  push:
    branches:
      - master
  # schedule:
    # - cron: '0 11 * * MON-FRI'
  repository_dispatch:
    types: 
      [publish_production]
  workflow_dispatch:

# Jobs to carry out
jobs:
  build:
    # Operating system to run job on
    runs-on: ubuntu-latest
    # Environment to run job on
    environment: backup
    # Environment variables
    env:
      DRUPAL_CONCURRENT_FILE_REQUESTS: 20
      DRUPAL_REQUEST_TIMEOUT: 6000000
      DRUPAL_URL: ${{ vars.DRUPAL_URL }}
      ROBOTSTXT_MODE: 'production'
      CONTEXT: 'production'
    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      # Install NodeJS
      - name: Install latest LTS version of Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: lts/*
          check-latest: true
      # Enabling cache
      - name: Caching Gatsby
        id: gatsby-cache-build
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: |
            public
            .cache
          key: ${{ runner.os }}-gatsby-build-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-gatsby-build-
      # Run npm ci (clean-install) and build on our code
      - run: npm ci
      - run: npm run build
      # Deploy to s3
      - name: Set s3 bucket credentials
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # v6.0.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Copy files to s3
        run: aws s3 sync ./public s3://lib-umich-backup
      # Notify Slack if build fails
      - name: Send custom JSON data to Slack workflow
        if: ${{ failure() }}
        uses: slackapi/slack-github-action@91efab103c0de0a537f72a35f6b8cda0ee76bf0a # v2.1.1
        with:
          webhook-type: webhook-trigger
          payload: |
            {
              "url": "https://github.com/mlibrary/lib.umich.edu/actions/runs/${{ github.run_id }}",
              "message": "Backup failed"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
      # Trigger production workflow if this workflow was triggered by push to master
      - name: Checking workflow method and triggering next workflow if needed
        if: ${{ success() && github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        uses: peter-evans/repository-dispatch@28959ce8df70de7be546dd1250a005dd32156697 # v4.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: backup_complete
